#!/usr/bin/env python3
"""Generate GMTAB.H for OPL4MID from doc/YRW801-GMMAP.TXT.

Zones sampled at notes 36/48/60/72/84; key ranges split halfway between.
Each cell is one wave or a layered pair "a/b".  Roots are NOT measured yet
(VEW2MAP /FULL, vendor boot); until then each entry's root is the mean of
the zone notes where that wave appears in its program row - the wave was
chosen by the vendor renderer for those regions, so its root is near them.
"""
import re, sys, statistics, pathlib

SRC = pathlib.Path(__file__).parent.parent / "doc" / "YRW801-GMMAP.TXT"
OUT = pathlib.Path(__file__).parent / "GMTAB.H"
ZONES = [36, 48, 60, 72, 84]

rows = {}
for line in SRC.read_text().splitlines():
    m = re.match(r"\s*(\d+)\s*\|\s*(.+)", line)
    if not m or m.group(2).startswith("n36"):
        continue
    prog = int(m.group(1))
    cells = m.group(2).split()
    cells = [c for c in cells if c != "LAYERED"]
    assert len(cells) == 5, (prog, cells)
    parsed = []
    for c in cells:
        w = sorted(int(x) for x in c.split("/"))
        assert 1 <= len(w) <= 2 and all(0 <= x <= 383 for x in w), (prog, c)
        parsed.append(w)
    rows[prog] = parsed
assert sorted(rows) == list(range(128)), sorted(rows)

def roots(row):
    seen = {}
    for zn, ws in zip(ZONES, row):
        for w in ws:
            seen.setdefault(w, []).append(zn)
    return {w: round(statistics.mean(z)) for w, z in seen.items()}

lines = [
    "/* GMTAB.H - generated by gengmtab.py from doc/YRW801-GMMAP.TXT.",
    " * Do not hand-edit.  5 key zones per GM program, split at 42/54/66/78;",
    " * up to 2 layers per zone; wave 0xFFFF = no second layer.",
    " * Roots are DERIVED (mean zone of each wave in its row), not measured;",
    " * regenerate after the VEW2MAP /FULL root capture. */",
    "",
    "typedef struct { unsigned wave[2]; unsigned char root[2]; } GMZONE;",
    "",
    "static const GMZONE gmtab[128][5] = {",
]
for prog in range(128):
    row = rows[prog]
    rt = roots(row)
    cells = []
    for ws in row:
        w0 = ws[0]
        w1 = ws[1] if len(ws) == 2 else 0xFFFF
        r0 = rt[w0]
        r1 = rt[ws[1]] if len(ws) == 2 else 0
        cells.append("{{%3u,%s},{%2u,%2u}}" %
                     (w0, "0xFFFF" if w1 == 0xFFFF else "%5u" % w1, r0, r1))
    lines.append("/*%3d*/ {%s}," % (prog, ",".join(cells)))
lines.append("};")
lines.append("")
OUT.write_text("\r\n".join(lines) + "\r\n")

n_lay = sum(1 for p in rows if any(len(ws) == 2 for ws in rows[p]))
print(f"wrote {OUT.name}: 128 programs, {n_lay} with layered cells")
