#!/usr/bin/env python3
"""Generate OPL4TAB.H for OPL4MID from the ALSA opl4 driver sources.

Ports the YRW801 instrument tables (ref-alsa/yrw801.c) and the F-number
pitch map + volume table (ref-alsa/opl4_synth.c), both (c) 2003 Clemens
Ladisch, dual-licensed BSD-2-clause / GPL v2.  OPL4MID is GPL v2, so the
tables are used under the GPL option; keep the credit block intact.
"""
import re, pathlib

REF = pathlib.Path(__file__).parent / "ref-alsa"
OUT = pathlib.Path(__file__).parent / "OPL4TAB.H"

yrw = (REF / "yrw801.c").read_text()
syn = (REF / "opl4_synth.c").read_text()

# ---- region arrays ------------------------------------------------------
arrays = {}
for m in re.finditer(
        r"static const struct opl4_region regions(_\w+)\[\] = \{(.*?)\};",
        yrw, re.S):
    name, body = m.group(1), m.group(2)
    rows = []
    for r in re.finditer(r"\{(0x[0-9a-f]+), (0x[0-9a-f]+), \{([^}]*)\}\}", body):
        lo, hi = int(r.group(1), 16), int(r.group(2), 16)
        f = [int(x.strip(), 0) for x in r.group(3).split(",")]
        assert len(f) == 12, (name, r.group(0))
        # tone, pitch_offset, key_scaling, panpot, vibrato, tone_attenuate,
        # volume_factor, reg_lfo_vibrato, ad1, ld2, rc, tremolo
        rows.append((lo, hi, f[0], f[1], f[2], f[3], f[5], f[6],
                     f[7], f[8], f[9], f[10], f[11]))
    arrays[name] = rows

order = re.search(r"snd_yrw801_regions\[0x81\] = \{(.*?)\};", yrw, re.S).group(1)
progs = re.findall(r"REGION\((_\w+)\)", order)
assert len(progs) == 129, len(progs)          # 128 GM programs + drums

# ---- pitch map and volume table ----------------------------------------
pm = re.search(r"snd_opl4_pitch_map\[0x600\] = \{(.*?)\};", syn, re.S).group(1)
pitch_map = [int(x, 0) for x in re.findall(r"0x[0-9a-f]+", pm)]
assert len(pitch_map) == 0x600, len(pitch_map)

vt = re.search(r"snd_opl4_volume_table\[128\] = \{(.*?)\};", syn, re.S).group(1)
vol = [int(x) for x in re.findall(r"\d+", vt)]
assert len(vol) == 128, len(vol)

# ---- emit ---------------------------------------------------------------
flat, index, off = [], [], 0
for name in progs:
    rows = arrays[name]
    index.append((off, len(rows)))
    flat.extend(rows)
    off += len(rows)

L = [
 "/* OPL4TAB.H - generated by genalsa.py.  Do not hand-edit.",
 " *",
 " * YRW801 instrument regions, F-number pitch map and volume table ported",
 " * from the Linux ALSA opl4 driver (sound/drivers/opl4/yrw801.c and",
 " * opl4_synth.c), (c) 2003 Clemens Ladisch <clemens@ladisch.de>,",
 " * dual-licensed BSD-2-clause / GPL v2 - used here under GPL v2.",
 " * alsa_prog[0..127] = GM programs, alsa_prog[128] = drums (lookup by",
 " * note).  pofs is in 100/128-cent units (0x80 = 1 semitone). */",
 "",
 "typedef struct {",
 "    unsigned char  lo, hi;",
 "    unsigned short tone;",
 "    short          pofs;",
 "    unsigned char  ksc;",
 "    signed char    pan;",
 "    unsigned char  att, vf;",
 "    unsigned char  lfovib, ad1, ld2, rc, trem;",
 "} REGION;",
 "",
 "static const REGION alsa_reg[%d] = {" % len(flat),
]
for lo, hi, tone, pofs, ksc, pan, att, vf, lv, ad, ld, rc, tr in flat:
    L.append("{%3u,%3u,0x%03x,%6d,%3u,%2d,0x%02x,0x%02x,0x%02x,0x%02x,0x%02x,0x%02x,0x%02x},"
             % (lo, hi, tone, pofs, ksc, pan, att, vf, lv, ad, ld, rc, tr))
L.append("};")
L.append("")
L.append("static const struct { unsigned short base; unsigned char n; } alsa_prog[129] = {")
for base, n in index:
    L.append("{%4d,%2d}," % (base, n))
L.append("};")
L.append("")
L.append("static const unsigned char vol_tab[128] = {")
for i in range(0, 128, 16):
    L.append(",".join("%3d" % v for v in vol[i:i+16]) + ",")
L.append("};")
L.append("")
L.append("static const unsigned short pitch_map[0x600] = {")
for i in range(0, 0x600, 12):
    L.append(",".join("0x%03x" % v for v in pitch_map[i:i+12]) + ",")
L.append("};")
L.append("")

OUT.write_text("\r\n".join(L) + "\r\n")
drums = arrays[progs[128]]
print("wrote %s: %d regions (%d drum), %d bytes" %
      (OUT.name, len(flat), len(drums), OUT.stat().st_size))
