#!/usr/bin/env python3
"""Generate OPL4TAB.H for OPL4SYN/OPL4MID from the ALSA opl4 driver sources.

Ports the YRW801 instrument tables (ref-alsa/yrw801.c) and the volume table
(ref-alsa/opl4_synth.c), both (c) 2003 Clemens Ladisch, dual-licensed
BSD-2-clause / GPL v2.  OPL4SYN is GPL v2, so they are used under the GPL
option; keep the credit block intact.

The tables are packed for a resident TSR, not for readability.  They stay
compiled into the one binary - there is no data file to lose:

  * A region's level fields (ksc, pan, att, vf) and its five envelope
    register values repeat heavily - 610 regions draw on only 126 distinct
    level sets and 246 distinct envelope sets - so a region quotes each by
    a one-byte index instead of carrying it.  16 bytes a region becomes 8.
    (Interning WHOLE regions was measured and is pointless: 601 of the 610
    are unique once tone and pitch offset are included.)

  * ALSA's 1536-entry F-number table is exactly round(1024*2^(p/1536))-1024,
    so it is replaced by the 13 semitone knots and rounded interpolation
    between them: 3072 bytes become 26, at a worst case of 1 LSB - under
    0.9 cents, and smaller than the OPL4's own F-number quantisation.

  * A program's region count is the difference between neighbouring start
    indices, so only the starts are stored.

13476 bytes of tables become 7028.
"""
import re, pathlib

REF = pathlib.Path(__file__).parent / "ref-alsa"
OUT = pathlib.Path(__file__).parent / "OPL4TAB.H"

yrw = (REF / "yrw801.c").read_text()
syn = (REF / "opl4_synth.c").read_text()

# ---- region arrays ------------------------------------------------------
arrays = {}
for m in re.finditer(
        r"static const struct opl4_region regions(_\w+)\[\] = \{(.*?)\};",
        yrw, re.S):
    name, body = m.group(1), m.group(2)
    rows = []
    for r in re.finditer(r"\{(0x[0-9a-f]+), (0x[0-9a-f]+), \{([^}]*)\}\}", body):
        lo, hi = int(r.group(1), 16), int(r.group(2), 16)
        f = [int(x.strip(), 0) for x in r.group(3).split(",")]
        assert len(f) == 12, (name, r.group(0))
        # tone, pitch_offset, key_scaling, panpot, vibrato, tone_attenuate,
        # volume_factor, reg_lfo_vibrato, ad1, ld2, rc, tremolo
        rows.append(dict(lo=lo, hi=hi, tone=f[0], pofs=f[1],
                         lvl=(f[2], f[3], f[5], f[6]),
                         env=(f[7], f[8], f[9], f[10], f[11])))
    arrays[name] = rows

order = re.search(r"snd_yrw801_regions\[0x81\] = \{(.*?)\};", yrw, re.S).group(1)
progs = re.findall(r"REGION\((_\w+)\)", order)
assert len(progs) == 129, len(progs)          # 128 GM programs + drums

# ---- volume table -------------------------------------------------------
vt = re.search(r"snd_opl4_volume_table\[128\] = \{(.*?)\};", syn, re.S).group(1)
vol = [int(x) for x in re.findall(r"\d+", vt)]
assert len(vol) == 128, len(vol)

# ---- the F-number table is a formula; prove that before dropping it -----
pm = re.search(r"snd_opl4_pitch_map\[0x600\] = \{(.*?)\};", syn, re.S).group(1)
pitch_map = [int(x, 0) for x in re.findall(r"0x[0-9a-f]+", pm)]
assert len(pitch_map) == 0x600
semi = [round(1024 * 2 ** (s / 12.0)) for s in range(13)]
worst = 0
for p in range(0x600):
    s, f = p >> 7, p & 127
    v = semi[s] + ((semi[s + 1] - semi[s]) * f + 64) // 128 - 1024
    worst = max(worst, abs(v - pitch_map[p]))
assert worst <= 1, "semitone interpolation drifted: %d LSB" % worst

# ---- intern the level and envelope sets ---------------------------------
flat, index, off = [], [], 0
for name in progs:
    index.append(off)
    flat.extend(arrays[name])
    off += len(arrays[name])
index.append(off)                             # sentinel: count = next - this

lvls, envs = [], []
for r in flat:
    for key, pool in (("lvl", lvls), ("env", envs)):
        if r[key] not in pool:
            pool.append(r[key])
        r[key + "_i"] = pool.index(r[key])
assert len(lvls) < 256 and len(envs) < 256, (len(lvls), len(envs))

# ---- emit ---------------------------------------------------------------
L = [
 "/* OPL4TAB.H - generated by genalsa.py.  Do not hand-edit.",
 " *",
 " * YRW801 instrument regions and the volume table ported from the Linux",
 " * ALSA opl4 driver (sound/drivers/opl4/yrw801.c and opl4_synth.c),",
 " * (c) 2003 Clemens Ladisch <clemens@ladisch.de>, dual-licensed",
 " * BSD-2-clause / GPL v2 - used here under GPL v2.",
 " *",
 " * A region quotes its level and envelope sets by index (%d and %d"
 " distinct",
 " * sets across %d regions), and the F-number table is computed from 13",
 " * semitone knots rather than stored.  Read regions through the RG_*",
 " * accessors and pitch through pitch_fnum(); nothing outside this header",
 " * should know how any of it is packed.",
 " *",
 " * alsa_prog[0..127] = GM programs, alsa_prog[128] = drums (lookup by",
 " * note); a program's regions run from alsa_reg[alsa_prog[p]] up to",
 " * alsa_prog[p+1].  pofs is in 100/128-cent units (0x80 = 1 semitone). */",
 "",
 "typedef struct {",
 "    unsigned char  lo, hi;      /* key range                            */",
 "    unsigned short tone;        /* wave number, 0-511                   */",
 "    short          pofs;        /* pitch offset, 100/128-cent units     */",
 "    unsigned char  lvl, env;    /* -> alsa_lvl[], alsa_env[]            */",
 "} REGION;",
 "",
 "typedef struct { unsigned char ksc; signed char pan;",
 "                 unsigned char att, vf; } RLVL;",
 "typedef struct { unsigned char lfovib, ad1, ld2, rc, trem; } RENV;",
 "",
]
L = [s % (len(lvls), len(envs)) if s.count("%d") == 2 else
     s % len(flat) if "%d" in s else s for s in L]

L.append("static const RLVL alsa_lvl[%d] = {" % len(lvls))
for ksc, pan, att, vf in lvls:
    L.append("{%3u,%3d,0x%02x,0x%02x}," % (ksc, pan, att, vf))
L.append("};")
L.append("")
L.append("static const RENV alsa_env[%d] = {" % len(envs))
for e in envs:
    L.append("{0x%02x,0x%02x,0x%02x,0x%02x,0x%02x}," % e)
L.append("};")
L.append("")
L.append("static const REGION alsa_reg[%d] = {" % len(flat))
for r in flat:
    L.append("{%3u,%3u,0x%03x,%6d,%3u,%3u}," %
             (r["lo"], r["hi"], r["tone"], r["pofs"], r["lvl_i"], r["env_i"]))
L.append("};")
L.append("")
L.append("static const unsigned short alsa_prog[%d] = {" % len(index))
for i in range(0, len(index), 10):
    L.append(",".join("%4d" % v for v in index[i:i + 10]) + ",")
L.append("};")
L.append("")
L.append("static const unsigned char vol_tab[128] = {")
for i in range(0, 128, 16):
    L.append(",".join("%3d" % v for v in vol[i:i + 16]) + ",")
L.append("};")
L.append("")
L.append("/* 1024 * 2^(s/12): the knots the F-number is interpolated between */")
L.append("static const unsigned short semi_tab[13] = {")
L.append(",".join("%5d" % v for v in semi) + "};")
L.append("")
L.append("#define RG_KSC(r)    (alsa_lvl[(r)->lvl].ksc)")
L.append("#define RG_PAN(r)    (alsa_lvl[(r)->lvl].pan)")
L.append("#define RG_ATT(r)    (alsa_lvl[(r)->lvl].att)")
L.append("#define RG_VF(r)     (alsa_lvl[(r)->lvl].vf)")
L.append("#define RG_LFOVIB(r) (alsa_env[(r)->env].lfovib)")
L.append("#define RG_AD1(r)    (alsa_env[(r)->env].ad1)")
L.append("#define RG_LD2(r)    (alsa_env[(r)->env].ld2)")
L.append("#define RG_RC(r)     (alsa_env[(r)->env].rc)")
L.append("#define RG_TREM(r)   (alsa_env[(r)->env].trem)")
L.append("")
L.append("/* p is 0..0x5FF, one octave in 100/128-cent units */")
L.append("static unsigned pitch_fnum(unsigned p)")
L.append("{")
L.append("    unsigned s = p >> 7, f = p & 127;")
L.append("    unsigned a = semi_tab[s], b = semi_tab[s + 1];")
L.append("    return a + (((b - a) * f + 64) >> 7) - 1024;")
L.append("}")
L.append("")

OUT.write_text("\r\n".join(L) + "\r\n")

size = (len(flat) * 8 + len(lvls) * 4 + len(envs) * 5 +
        len(index) * 2 + 128 + 26)
print("wrote %s: %d regions, %d level sets, %d envelope sets" %
      (OUT.name, len(flat), len(lvls), len(envs)))
print("  tables now %d bytes (was 13476), pitch interp worst case %d LSB"
      % (size, worst))
