/* OPL4MID.C - CF-VEW212: play a Standard MIDI File on the OPL4 wavetable.
 *
 * Native DOS, no vendor software: the card is brought up by VEW21XGO on COR
 * index 23h (codec 530-539 + OPL4 388-38D) and this drives the OPL4's 24
 * wave voices directly.  No MPU-401 is involved - the 212 has none on index
 * 23h, and a file player does not need one.  Games that write MPU ports are
 * a later job for MPUSHIM feeding this same engine.
 *
 * INSTRUMENTS (OPL4TAB.H, generated by genalsa.py):
 *   YRW801 region tables, pitch map and volume table ported from the Linux
 *   ALSA opl4 driver - sound/drivers/opl4/yrw801.c and opl4_synth.c,
 *   (c) 2003 Clemens Ladisch <clemens@ladisch.de>, dual-licensed
 *   BSD-2-clause / GPL v2.  The voice programming sequence (tone number
 *   bit 8 before the LSB that triggers the header load; pan, pitch and
 *   level during the load; envelope overrides after it; then KEY ON)
 *   follows the same driver.  Cross-checked against our own hardware
 *   captures doc/YRW801-WAVES.TXT and doc/YRW801-GMMAP.TXT in the
 *   vew21xgo repo.
 *
 * CARD FACTS (measured on the CF-VEW212, 2026-08-28):
 *   - Only DO2 (FM + wave mixed) is wired to the codec's line input, so
 *     every voice is keyed with CH = 0.  CH = 1 is silence on this card.
 *   - F9 is the PCM mix level into DO2, 3 bits per side, 3 dB a step.
 *
 * TIMING: polls PIT channel 0 against the BIOS tick, ~0.84 us resolution,
 * and installs no interrupt handler of its own.
 *
 * Usage: OPL4MID <file.mid> [/TL=n] [/MIX=n] [/PAN=n] [/LOOP] [/LIST] [/V]
 *                [/BASE=388] [/?]
 *   /TL=n     master attenuation 0-127 added to every voice   (default 0)
 *   /MIX=n    F9 PCM mix, 0-7, 3 dB a step, 0 = loudest       (default 0)
 *   /PAN=n    fixed panpot -7..7, overriding the per-region value
 *   /LOOP     repeat until a key is pressed
 *   /LIST     parse and report, play nothing
 *   /V        trace note events
 *
 * Build: C:\WATCOM\BLD.BAT OPL4MID
 *
 * License: GPL v2 (the ALSA tables above require it and it is welcome).
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <malloc.h>
#include <conio.h>
#include <dos.h>

/* ---- OPL4 -------------------------------------------------------------- */
static unsigned BASE = 0x388;
#define FMA1  (BASE + 2)
#define FMD1  (BASE + 3)
#define WADDR (BASE + 4)
#define WDATA (BASE + 5)

static void iod(unsigned n){ while (n--) (void)inp(0x80); }

static unsigned char wv_get(unsigned char r)
{
    outp(WADDR, r); iod(40);
    return (unsigned char)inp(WDATA);
}
static void wv_put(unsigned char r, unsigned char v)
{
    outp(WADDR, r); iod(40);
    outp(WDATA, v); iod(40);
}
static void new2(int on)
{
    outp(FMA1, 0x05); iod(40);
    outp(FMD1, on ? 0x03 : 0x00); iod(40);
}

#include "OPL4TAB.H"

/* ---- microsecond clock: PIT ch0 read against the BIOS tick -------------- */
static unsigned long now_us(void)
{
    unsigned long t1, t2;
    unsigned c;
    unsigned char lo, hi;
    int guard = 4;
    do {
        t1 = *(unsigned long __far *)MK_FP(0x0040, 0x006C);
        outp(0x43, 0x00);                       /* latch counter 0          */
        lo = (unsigned char)inp(0x40);
        hi = (unsigned char)inp(0x40);
        t2 = *(unsigned long __far *)MK_FP(0x0040, 0x006C);
    } while (t1 != t2 && --guard);
    c = ((unsigned)hi << 8) | lo;               /* counts DOWN from 65536   */
    return t1 * 54925UL + ((65536UL - c) * 54925UL) / 65536UL;
}
static unsigned long t0;
static void wait_until(unsigned long us)
{
    while ((now_us() - t0) < us) {
        if (kbhit()) return;
    }
}

/* ---- voices ------------------------------------------------------------ */
#define NVOICE 24
typedef struct { int ch, note, on; unsigned long age; unsigned char misc; } VOICE;
static VOICE vc[NVOICE];
static unsigned long agec = 1;

static int  o_tl = 0, o_pan = -99, o_verb = 0;
static int  chprog[16], chvol[16];

static void voice_off(int v)
{
    vc[v].misc &= 0x7F;                                  /* KEY ON off      */
    wv_put((unsigned char)(0x68 + v), vc[v].misc);
    vc[v].on = 0;
}

static int voice_alloc(void)
{
    int i, best = 0;
    unsigned long oldest = 0xFFFFFFFFUL;
    for (i = 0; i < NVOICE; i++) if (!vc[i].on) return i;
    for (i = 0; i < NVOICE; i++) if (vc[i].age < oldest) { oldest = vc[i].age; best = i; }
    voice_off(best);
    return best;
}

static void all_off(void)
{
    int i;
    for (i = 0; i < NVOICE; i++) voice_off(i);
}

static void note_off(int ch, int note)
{
    int v;
    for (v = 0; v < NVOICE; v++)
        if (vc[v].on && vc[v].ch == ch && vc[v].note == note) voice_off(v);
}

/* Start one region of a note.  pnote carries the pitch (60 for drums). */
static void start_region(int ch, int note, int pnote, int vel,
                         const REGION *rg)
{
    int v, att, pan, octv;
    long pitch;
    unsigned f;

    v = voice_alloc();
    vc[v].ch = ch; vc[v].note = note; vc[v].on = 1; vc[v].age = agec++;

    /* tone number bit 8 must be latched in 20h BEFORE the 08h write -
     * that write triggers the 12-byte header fetch from the YRW801. */
    wv_put((unsigned char)(0x20 + v), (unsigned char)((rg->tone >> 8) & 1));
    wv_put((unsigned char)(0x08 + v), (unsigned char)(rg->tone & 0xFF));

    /* pan + LFO reset; safe while the header loads */
    pan = o_pan != -99 ? o_pan : RG_PAN(rg);
    if (pan < -7) pan = -7;
    if (pan >  7) pan =  7;
    vc[v].misc = (unsigned char)(0x20 | (pan & 0x0F));
    wv_put((unsigned char)(0x68 + v), vc[v].misc);

    /* pitch, in 100/128-cent units: 0x80 = 1 semitone, 0x600 = 1 octave */
    pitch = (((long)(pnote - 60) << 7) * RG_KSC(rg)) / 100 + (60L << 7);
    pitch += rg->pofs;
    if (pitch < 0)        pitch = 0;
    if (pitch >= 0x6000L) pitch = 0x5FFFL;
    octv = (int)(pitch / 0x600) - 8;
    f = pitch_fnum((unsigned)(pitch % 0x600));
    wv_put((unsigned char)(0x20 + v),
           (unsigned char)(((f & 0x7F) << 1) | ((rg->tone >> 8) & 1)));
    wv_put((unsigned char)(0x38 + v),
           (unsigned char)(((octv & 0x0F) << 4) | ((f >> 7) & 0x07)));

    /* level: attenuations add, then the region's volume factor scales */
    att = RG_ATT(rg) + vol_tab[chvol[ch] & 0x7F] + vol_tab[vel & 0x7F];
    att = 0x7F - ((0x7F - att) * RG_VF(rg)) / 0xFE;
    att += o_tl;
    if (att < 0)    att = 0;
    if (att > 0x7E) att = 0x7E;
    wv_put((unsigned char)(0x50 + v), (unsigned char)((att << 1) | 1));

    /* envelope overrides only after the header load ends, or the loaded
     * header would clobber them */
    { int t = 200; while ((inp(BASE) & 0x02) && --t) iod(8); }
    wv_put((unsigned char)(0x80 + v), RG_LFOVIB(rg));
    wv_put((unsigned char)(0x98 + v), RG_AD1(rg));
    wv_put((unsigned char)(0xB0 + v), RG_LD2(rg));
    wv_put((unsigned char)(0xC8 + v), RG_RC(rg));
    wv_put((unsigned char)(0xE0 + v), RG_TREM(rg));

    vc[v].misc = (unsigned char)((vc[v].misc & 0x1F) | 0x80);   /* KEY ON */
    wv_put((unsigned char)(0x68 + v), vc[v].misc);

    if (o_verb) printf("ch%02d n%03d v%03d -> voice %d tone %u att %d\r\n",
                       ch, note, vel, v, rg->tone, att);
}

static void note_on(int ch, int note, int vel)
{
    int i, n = 0, prog;
    unsigned base, cnt;
    if (vel == 0) { note_off(ch, note); return; }
    prog = ch == 9 ? 128 : (chprog[ch] & 0x7F);
    base = alsa_prog[prog];
    cnt  = alsa_prog[prog + 1] - base;
    for (i = 0; i < (int)cnt && n < 2; i++) {
        const REGION *rg = &alsa_reg[base + i];
        if (note >= rg->lo && note <= rg->hi) {
            start_region(ch, note, ch == 9 ? 60 : note, vel, rg);
            n++;
        }
    }
    if (o_verb && n == 0) printf("ch%02d n%03d: no region\r\n", ch, note);
}

/* ---- SMF --------------------------------------------------------------- */
#define MAXTRK 32
#define MAXFILE 64000U
static unsigned char __far *fb;
static unsigned long fsize;

typedef struct {
    unsigned long pos, end, tick;
    unsigned char rs;
    int done;
} TRK;
static TRK tk[MAXTRK];
static int ntrk;

static unsigned char  rd8 (unsigned long p){ return fb[p]; }
static unsigned       rd16(unsigned long p){ return ((unsigned)fb[p]<<8)|fb[p+1]; }
static unsigned long  rd32(unsigned long p)
{
    return ((unsigned long)fb[p]<<24)|((unsigned long)fb[p+1]<<16)|
           ((unsigned long)fb[p+2]<<8)|fb[p+3];
}
static unsigned long vlq(unsigned long *p)
{
    unsigned long v = 0;
    unsigned char c;
    int n = 0;
    do { c = fb[(*p)++]; v = (v << 7) | (c & 0x7F); } while ((c & 0x80) && ++n < 4);
    return v;
}

int main(int argc, char **argv)
{
    char *fname = 0;
    int i, loop = 0, list = 0, mix = 0, opened = 0;
    unsigned long division = 96, tempo = 500000UL, us = 0, lasttick = 0;
    FILE *f;
    unsigned char id;

    for (i = 1; i < argc; i++) {
        char *p = argv[i];
        if (p[0] != '/' && p[0] != '-') { fname = p; continue; }
        if (p[1] == '?') {
            printf("OPL4MID <file.mid> [/TL=n] [/MIX=n] [/PAN=n] [/LOOP]\r\n");
            printf("        [/LIST] [/V] [/BASE=388]\r\n");
            printf("Needs the card on COR index 23h (run VEW21XGO first).\r\n");
            return 0;
        }
        if      (!strnicmp(p+1,"BASE",4)) BASE   = (unsigned)strtol(p+5+(p[5]=='='),0,16);
        else if (!strnicmp(p+1,"LOOP",4)) loop   = 1;
        else if (!strnicmp(p+1,"LIST",4)) list   = 1;
        else if (!strnicmp(p+1,"MIX",3))  mix    = (int)strtol(p+4+(p[4]=='='),0,0);
        else if (!strnicmp(p+1,"PAN",3))  o_pan  = (int)strtol(p+4+(p[4]=='='),0,0);
        else if (!strnicmp(p+1,"TL",2))   o_tl   = (int)strtol(p+3+(p[3]=='='),0,0);
        else if (p[1]=='V' || p[1]=='v')  o_verb = 1;
    }
    if (!fname) { printf("OPL4MID: no file given (/? for usage)\r\n"); return 1; }

    /* ---- load ---------------------------------------------------------- */
    f = fopen(fname, "rb");
    if (!f) { printf("cannot open %s\r\n", fname); return 1; }
    fseek(f, 0, SEEK_END); fsize = ftell(f); fseek(f, 0, SEEK_SET);
    if (fsize < 22 || fsize > MAXFILE) {
        printf("%s is %lu bytes - this build handles 22..%u\r\n",
               fname, fsize, MAXFILE);
        fclose(f); return 1;
    }
    fb = (unsigned char __far *)_fmalloc((unsigned)fsize);
    if (!fb) { printf("out of memory\r\n"); fclose(f); return 1; }
    {   /* fread into a far buffer, in chunks the small-model call can take */
        unsigned long got = 0;
        while (got < fsize) {
            unsigned char tmp[512];
            unsigned want = (unsigned)((fsize - got) > 512 ? 512 : (fsize - got));
            unsigned n = (unsigned)fread(tmp, 1, want, f);
            if (!n) break;
            for (i = 0; i < (int)n; i++) fb[got + i] = tmp[i];
            got += n;
        }
        fsize = got;
    }
    fclose(f);

    if (rd32(0) != 0x4D546864UL) { printf("not a MIDI file (no MThd)\r\n"); return 1; }
    division = rd16(12);
    ntrk     = (int)rd16(10);
    printf("%s: format %u, %d tracks, division %lu\r\n",
           fname, rd16(8), ntrk, division);
    if (division & 0x8000UL) { printf("SMPTE timing is not supported\r\n"); return 1; }
    if (ntrk > MAXTRK) { printf("more than %d tracks - truncating\r\n", MAXTRK); ntrk = MAXTRK; }

    {   /* walk the chunk list */
        unsigned long p = 14;
        int t = 0;
        while (p + 8 <= fsize && t < ntrk) {
            unsigned long len = rd32(p + 4);
            if (rd32(p) == 0x4D54726BUL) {
                tk[t].pos  = p + 8;
                tk[t].end  = p + 8 + len;
                if (tk[t].end > fsize) tk[t].end = fsize;
                tk[t].rs   = 0;
                tk[t].done = 0;
                tk[t].tick = tk[t].pos < tk[t].end ? vlq(&tk[t].pos) : 0;
                t++;
            }
            p += 8 + len;
        }
        ntrk = t;
        printf("parsed %d track(s)\r\n", ntrk);
    }
    if (list) { _ffree(fb); return 0; }

    /* ---- OPL4 up ------------------------------------------------------- */
    /* Always open the gate - see VEW2ROM.C: a closed bus floats and has
     * been seen to float to 20h, the real Device ID's value. */
    new2(1); opened = 1;
    id = wv_get(0x02);
    if ((id & 0xF0) != 0x20) {
        printf("DevID %02X: no OPL4 at %03X - run VEW21XGO first.\r\n", id, BASE);
        if (opened) new2(0);
        _ffree(fb); return 1;
    }
    wv_put(0x02, 0x00);                                  /* sound generation */
    if (mix < 0) mix = 0; if (mix > 7) mix = 7;
    wv_put(0xF9, (unsigned char)(((mix & 7) << 3) | (mix & 7)));
    for (i = 0; i < 16; i++) { chprog[i] = 0; chvol[i] = 100; }
    all_off();

    printf("playing - any key stops\r\n");

    do {
        int t;
        {   /* re-seek every track to its first event */
            unsigned long p = 14;
            int n = 0;
            while (p + 8 <= fsize && n < ntrk) {
                unsigned long len = rd32(p + 4);
                if (rd32(p) == 0x4D54726BUL) {
                    tk[n].pos = p + 8; tk[n].end = p + 8 + len;
                    if (tk[n].end > fsize) tk[n].end = fsize;
                    tk[n].rs = 0; tk[n].done = 0;
                    tk[n].tick = tk[n].pos < tk[n].end ? vlq(&tk[n].pos) : 0;
                    n++;
                }
                p += 8 + len;
            }
        }
        tempo = 500000UL; us = 0; lasttick = 0;
        t0 = now_us();

        for (;;) {
            int best = -1, done = 1;
            unsigned long bt = 0xFFFFFFFFUL;
            unsigned char st;

            for (t = 0; t < ntrk; t++)
                if (!tk[t].done) { done = 0; if (tk[t].tick < bt) { bt = tk[t].tick; best = t; } }
            if (done || best < 0) break;
            if (kbhit()) { (void)getch(); goto stop; }

            us += ((bt - lasttick) * tempo) / division;
            lasttick = bt;
            wait_until(us);
            if (kbhit()) { (void)getch(); goto stop; }

            st = rd8(tk[best].pos);
            if (st & 0x80) tk[best].pos++; else st = tk[best].rs;
            if (st < 0xF0) tk[best].rs = st;

            if (st == 0xFF) {
                unsigned char m = rd8(tk[best].pos++);
                unsigned long l = vlq(&tk[best].pos);
                if (m == 0x51 && l == 3)
                    tempo = ((unsigned long)rd8(tk[best].pos) << 16) |
                            ((unsigned long)rd8(tk[best].pos+1) << 8) |
                             (unsigned long)rd8(tk[best].pos+2);
                if (m == 0x2F) tk[best].done = 1;
                tk[best].pos += l;
            } else if (st == 0xF0 || st == 0xF7) {
                unsigned long l = vlq(&tk[best].pos);
                tk[best].pos += l;
            } else {
                int ch = st & 0x0F, a, b;
                switch (st & 0xF0) {
                case 0x80: a = rd8(tk[best].pos++); b = rd8(tk[best].pos++);
                           note_off(ch, a); break;
                case 0x90: a = rd8(tk[best].pos++); b = rd8(tk[best].pos++);
                           note_on(ch, a, b); break;
                case 0xA0: tk[best].pos += 2; break;
                case 0xB0: a = rd8(tk[best].pos++); b = rd8(tk[best].pos++);
                           if (a == 7) chvol[ch] = b;
                           if (a == 120 || a == 123) {
                               int v; for (v = 0; v < NVOICE; v++)
                                   if (vc[v].on && vc[v].ch == ch) voice_off(v);
                           }
                           break;
                case 0xC0: chprog[ch] = rd8(tk[best].pos++); break;
                case 0xD0: tk[best].pos += 1; break;
                case 0xE0: tk[best].pos += 2; break;
                default:   tk[best].done = 1; break;
                }
            }
            if (tk[best].pos >= tk[best].end) tk[best].done = 1;
            else if (!tk[best].done) tk[best].tick += vlq(&tk[best].pos);
        }
    } while (loop);

stop:
    all_off();
    if (opened) new2(0);
    _ffree(fb);
    printf("done.\r\n");
    return 0;
}
